apiVersion: 1

datasources:
  - name: DepTracker Postgres
    uid: deptracker-pg
    type: postgres
    access: proxy
    url: postgres:5432
    user: deptracker
    jsonData:
      database: deptracker
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: deptracker
    isDefault: true
